jobs:
- job:
  pool: ci-agent-pool
  timeoutInMinutes: 600
  variables:
  - group: Image Generation Variables

  steps:

  - task: PowerShell@2
    displayName: 'Create deployment release'
    inputs:
      targetType: filePath
      filePath: ./images.CI/create-release.ps1
      arguments: -BuildId $(Build.BuildNumber) `
                        -Organization $(RELEASE_TARGET_ORGANIZATION) `
                        -DefinitionId $(RELEASE_TARGET_DEFINITION_ID) `
                        -Project $(RELEASE_TARGET_PROJECT) `
                        -ImageName ${{ parameters.image_type }} `
                        -AccessToken $(RELEASE_TARGET_TOKEN)


  - task: PowerShell@2
    displayName: 'Clean up resources'
    condition: always()
    inputs:
      targetType: filePath
      filePath: ./images.CI/cleanup.ps1
      arguments: -ResourcesNamePrefix $(Build.BuildNumber) `
                     -ClientId $(CLIENT_ID) `
                     -ClientSecret $(CLIENT_SECRET) `
                     -Image ${{ parameters.image_type }} `
                     -SubscriptionId $(AZURE_SUBSCRIPTION) `
                     -TenantId $(AZURE_TENANT)
