schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - master
  always: true

trigger: 
  batch: false
  branches:
    include: master
pr:
  autoCancel: true
  branches:
    include:
    - master

jobs:
- template: image-generation.yml
  parameters:
    image_type: Windows2019-Azure
